### ISSUE TITLE
Basic example minor fix 

### ISSUE THREAD

**Issue by kimgysen** [Clariity/react-chessboard#48] opened 2022-11-20 22:48 UTC
In the basic example, I see the following line:  

`const gameCopy = { ...game };`

I don't think this will work, because the copy will only inherit the enumerable properties, instead of the prototype's methods. 

Therefore the following line will fail: 

`const result = gameCopy.move(move);`

Easily fixed with using: 

`const gameCopy = Object.create(game);`

**Comment by Clariity** [comment] 2022-11-21 09:27
Have you tried using the basic example code?

I believe it does work, I use the same logic in my chessopenings.co.uk website

**Comment by kimgysen** [comment] 2022-11-21 09:53
Yes, it's strange that it does work for you then. 
The following code I have is the same as the demo: 

![image](https://user-images.githubusercontent.com/4547364/203019481-ff039795-67ed-46ba-8ae2-b32ce902529c.png)

The first log: 
![image](https://user-images.githubusercontent.com/4547364/203019858-f83e21b1-322c-4b75-8109-5f87cdf36b6b.png)

The copy: 
![image](https://user-images.githubusercontent.com/4547364/203019978-a3facaef-5861-4c49-8461-430f10313f00.png)

Object.create fixed it for me. Unless I'm missing something, the docs aren't too clear but it would appear that the prototype was not copied for me.

**Comment by Clariity** [comment] 2022-11-21 10:09
![image](https://user-images.githubusercontent.com/30983280/203021443-75266b34-47d8-4db2-86d2-80328c03da67.png)

This is the object in production at react-chessboard.com, showing the move() function available in the gameCopy

The spread operator should copy over the functions from the game object, no idea why they are in your prototype object as they aren't prototype methods

What node version are you using out of curiosity?

**Comment by kimgysen** [comment] 2022-11-21 10:12
I'm not sure what you mean; methods are always per default on the prototype object (?). 
I upgrade yesterday to Node version v19.1.0.

**Comment by Clariity** [comment] 2022-11-21 10:28
![image](https://user-images.githubusercontent.com/30983280/203027474-44c539bd-48c9-4720-9065-2bdf7d6033c3.png)

**Comment by Clariity** [comment] 2022-11-21 10:28
can you try downgrading to node 16 and see what happens?

**Comment by Clariity** [comment] 2022-11-21 10:46
also what version of Chess.js are you using?

**Comment by kimgysen** [comment] 2022-11-21 10:50
Sorry, I prefer not to downgrade currently, as I'm working on other projects. 
The versions used are: 
![image](https://user-images.githubusercontent.com/4547364/203032049-974a2c9b-9729-4302-947d-6a68cd7489e3.png)

**Comment by kimgysen** [comment] 2022-11-21 11:02
What I meant is that I'm used to methods in JS being on the prototype object, because it helps with inheritance in the prototype chain. Perhaps they've changed this behavior in the chess.js lib compared to previous versions (?). 
Btw nice lib!

**Comment by Clariity** [comment] 2022-11-21 12:58
You can use nvm to move between node versions quickly, might be worth giving it a try on node 16 and also using chess.js 0.12.0 to see if that fixes anything

**Comment by kimgysen** [comment] 2022-11-21 14:15
It's not a blocking issue for me, I just thought to send a ping with my experience. For me you can close the issue.

**Comment by Clariity** [comment] 2022-11-21 14:26
It may be an issue if Node 19 and Chess.js 1.0.0 mean the examples are incorrect

Thank you for raising it, I will look into it further when I have time

**Comment by saumikn** [comment] 2022-11-21 18:25
I'm trying to recreate the basic example, and I couldn't get the random move working, it would generate the chosen and the random response, but only render the chosen move. Here's the code that I got working for player vs player. I had to edit the promotion logic, as the new version of chess.js fails if you add promotion but the move isn't a promoting move.

```typescript
import React, { useState } from 'react';
import { Chess, Square, Move } from "chess.js";
import { Chessboard } from "react-chessboard";

interface ShortMove {
  from: Square;
  to: Square;
  promotion?: string;
}

export default function App() {
  const [game, setGame] = useState(new Chess());

  function makeAMove(move: ShortMove) : Move | null {
    const gameCopy: Chess = Object.create(game);
    const result = gameCopy.move(move);
    setGame(gameCopy);
    return result; // null if the move was illegal, the move object if the move was legal
  }

  function onDrop(sourceSquare: Square, targetSquare: Square): boolean {
    const gameCopy: Chess = Object.create(game);
    if (makeAMove({ from: sourceSquare, to: targetSquare })) {
      return true;
    } else if (makeAMove({ from: sourceSquare, to: targetSquare, promotion: 'q' })) {
      return true;
    } else {
      return false;
    }
  }

  return (
    <>
      <Chessboard position={game.fen()} onPieceDrop={onDrop} />
      <p>{game.pgn()}</p>
    </>
  );
}
```

And my dependencies are:
```
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.3",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.9",
    "chess.js": "^1.0.0-alpha.0",
    "react": "^18.2.0",
    "react-chessboard": "^1.3.1",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.3",
    "web-vitals": "^2.1.4"
  },
```

**Comment by Clariity** [comment] 2022-11-21 18:31
if you use chess.js 0.12.0 does it work?

1.0.0 is in alpha and probably shouldn't be used yet

**Comment by Clariity** [comment] 2022-11-21 18:32
Please check the /example folder for all working examples shown at react-chessboard.com

https://github.com/Clariity/react-chessboard/blob/main/example/package.json

**Comment by saumikn** [comment] 2022-11-21 18:36
Actually, I'm able to get random moves working with the following code. The only thing I can't get is if I try using it with `setTimeout`, because then the page re-renders before the new move is made, and doesn't rerender after the timeout.

It probably would work with 0.12.0, but I'd prefer 1.0.0 alpha just because it has typescript defined natively in the package.

```typescript
import React, { useState } from 'react';
import { Chess, Square, Move } from "chess.js";
import { Chessboard } from "react-chessboard";

interface ShortMove {
  from: Square;
  to: Square;
  promotion?: string;
}

export default function App() {
  const [game, setGame] = useState(new Chess());
  const gameCopy: Chess = Object.create(game);

  function makeAMove(move: ShortMove | string) : Move | null {
    console.log(move);
    const result = gameCopy.move(move);
    setGame(gameCopy);
    return result; // null if the move was illegal, the move object if the move was legal
  }

  function makeRandomMove() {
    const possibleMoves = gameCopy.moves() as string[];
    if (gameCopy.isGameOver() || gameCopy.isDraw() || possibleMoves.length === 0)
      return; // exit if the game is over
    const randomIndex = Math.floor(Math.random() * possibleMoves.length);
    makeAMove(possibleMoves[randomIndex]);
  }

  function onDrop(sourceSquare: Square, targetSquare: Square): boolean {
    const gameCopy: Chess = Object.create(game);
    if (makeAMove({ from: sourceSquare, to: targetSquare })) {
      makeRandomMove();
      return true;
    } else if (makeAMove({ from: sourceSquare, to: targetSquare, promotion: 'q' })) {
      makeRandomMove();
      return true;
    } else {
      return false;
    }
  }

  return (
    <>
      <Chessboard position={game.fen()} onPieceDrop={onDrop} />
      <p>{game.pgn()}</p>
    </>
  );
}
```

**Comment by Clariity** [comment] 2022-11-21 18:38
https://github.com/Clariity/react-chessboard/blob/main/example/src/boards/PlayVsRandom.js

**Comment by christopherkade** [comment] 2022-12-20 22:18
@Clariity I can concur that the basic example throws an error:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/15229355/208775893-b52da5a8-d6d6-4214-a55f-9ae858a765d7.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/15229355/208775957-6134184c-eda5-4bea-949d-87f421d6510f.png">

Changing the `gameCopy` to `const gameCopy = Object.create(game);` does indeed copy the `.move` method over **but** the result returned is permanently `null` on my end despite being a legal move.

```jsx
import React, { useState } from "react";
import { Chessboard } from "react-chessboard";
import { Chess } from "chess.js";
import "./Board.css";

const Board = () => {
  const [game, setGame] = useState(new Chess());

  function makeAMove(move) {
    const gameCopy = Object.create(game);
    const result = gameCopy.move(move);

    // For some reason result is always null AND the pawn is not moved - despite playing a legal move
    setGame(gameCopy);
    return result;
  }

  function makeRandomMove() {
    const possibleMoves = game.moves();
    if (game.game_over() || game.in_draw() || possibleMoves.length === 0)
      return; // exit if the game is over
    const randomIndex = Math.floor(Math.random() * possibleMoves.length);
    makeAMove(possibleMoves[randomIndex]);
  }

  function onDrop(sourceSquare, targetSquare) {
    const move = makeAMove({
      from: sourceSquare,
      to: targetSquare,
      promotion: "q", // always promote to a queen for example simplicity
    });

    // illegal move
    if (move === null) return false;

    setTimeout(makeRandomMove, 200);
    return true;
  }

  return (
    <div className="container">
      <Chessboard id="basic-board" position={game.fen()} onPieceDrop={onDrop} />
    </div>
  );
};

export default Board;
```

Hope I'm sharing enough information, let me know if you need anything else to reproduce it. Thanks !

**Comment by Clariity** [comment] 2022-12-20 22:19
What version of Node and Chess.js are you using please?

**Comment by christopherkade** [comment] 2022-12-20 22:31
`chess.js: "^1.0.0-alpha.0`

`react-chessboard: "^1.3.1`

`node: v16.13.0`

**Comment by Clariity** [comment] 2022-12-20 22:34
Does this issue exist with chess.js 0.12.0

1.0.0 is in alpha and may introduce issues

**Comment by christopherkade** [comment] 2022-12-20 22:38
Good news, it works with `v0.12.0` ! (Side note, loadPgn is load_pgn at that version).

Thank you so much for your help

**Comment by Clariity** [comment] 2022-12-20 22:45
Closing issue as it's due to chess.js 1.0.0 being in alpha, hence unstable

For now, use chess.js 0.12.0

**Closed by Clariity** 2022-12-20 22:45 UTC
