### ISSUE TITLE
Super irritating Erroe - Invariant Violation: Expected drag drop context

### ISSUE THREAD

**Issue by shinebarbhuiya** [Clariity/react-chessboard#159] opened 2024-09-13 06:39 UTC
![image](https://github.com/user-attachments/assets/3ca411f6-0e5b-4834-ac10-5e32a6d7b846)

Please fix this issue for Nextjs

**Comment by LunarEclipseCode** [comment] 2024-09-13 14:32
Can you try switching from version 4.7.1 to 4.7.0 ? After making this change, I am not seeing this error anymore in my project.

**Comment by Clariity** [comment] 2024-09-14 15:24
Closing as duplicate of https://github.com/Clariity/react-chessboard/issues/158

**Closed by Clariity** 2024-09-14 15:24 UTC
